### ISSUE TITLE
Feature Request: make `len()` require no locks on shards

### ISSUE THREAD

**Issue by ClSlaid** [xacrimon/dashmap#239] opened 2022-11-05 08:27 UTC
Thank you for maintaining such a useful crate!

I've been using dashmap for a while, but recently, I came into trouble when implementing a limited-sized hashmap.

It's hoped that the entries stored in hashmap should never exceed the limit and that's how I'd like to implement it:

```rust
let entry = map.entry(key);
if map.len() < limit {
    // write to the entry
} else {
    // raise an Err
}
```

Surely you can see there is a deadlock since a mutable ref is gained by `dashmap::entry()`, then `dashmap::len()` requires immutable references on all shards.

So I came up with using an external atomic counter to record the real size of the map, but honestly, it's pretty hard to do it right, since there is pretty much code interfering with it.

```rust
// this cannot work, maybe the problem with memory ordering?

let entry = map.entry(key);
if counter.fetch_add(1, Ordering::Relaxed) < limit {
    // write to the entry
} else {
    counter.fetch_sub(1, Ordering::Relaxed);
    // raise an Err
}
```

------

If you have any suggestions on my algorithm above, please let me know.

**Comment by xacrimon** [comment] 2022-11-29 21:46
Hey, I'm going to close this. The problem is that keeping a counter is very expensive due to atomic contention and thus not something we can support.

**Closed by xacrimon** 2022-11-29 21:46 UTC
